config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
      resources :comments, :only => [:create, :destroy]
      resources :tasks, :except => [:destroy] do
        resources :subtasks, :only => [:create, :destroy, :update]
      end
      delete 'tasks/destroy_from_list', :to => 'tasks#destroy_from_list'
      delete 'tasks/destroy_from_show', :to => 'tasks#destroy_from_show'
    end
  end
  
  resources :members
  get 'home/index'

  get 'user', to: 'users#show'



  root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

end

app/models/project.rb
class Project < ApplicationRecord

  acts_as_tenant
  belongs_to :tenant
  validates_uniqueness_of :title
  has_many :comments, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :artifacts, dependent: :destroy
  has_many :subtasks, dependent: :destroy
  has_many :user_projects, :dependent => :destroy
  has_many :users, through: :user_projects

  validate :free_plan_can_only_have_one_project

  def free_plan_can_only_have_one_project
    if self.new_record? && (tenant.projects.count > 0) && (tenant.plan == 'free')
      errors.add(:base, "Free plan account can only have one project")
    end
  end

  def self.by_user_plan_and_tenant(tenant_id, user)
    tenant = Tenant.find(tenant_id)
    if tenant.plan == 'premium'
      if user.is_admin? || user.is_account_manager?
        tenant.projects
      else
        user.projects.where(tenant_id: tenant.id)
      end
    else
      if user.is_admin? || user.is_account_manager?
        tenant.projects.order(:id).limit(1)
      else
        user.projects.where(tenant_id: tenant.id).order(:id).limit(1)
      end
    end
  end

  def self.current_projects(tenant_id, user)
    tenant = Tenant.find(tenant_id)
    if tenant.plan == 'premium'
      if user.is_admin? || user.is_account_manager?
        tenant.projects.where("expected_start_date < ? AND expected_completion_date > ?", Date.today, Date.today)
      else
        user.projects.where("tenant_id = ? AND expected_start_date < ? AND expected_completion_date > ?", tenant.id, Date.today, Date.today)
      end
    else
      if user.is_admin? || user.is_account_manager?
        tenant.projects.where("expected_start_date < ? AND expected_completion_date > ?", Date.today, Date.today).order(:id).limit(1)
      else
        user.projects.where("tenant_id = ? AND expected_start_date < ? AND expected_completion_date > ?", tenant.id, Date.today, Date.today).order(:id).limit(1)
      end
    end
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :verify_tenant
  before_action :set_project, only: [:show, :edit, :update, :destroy, :users, :add_user]
  before_action :set_tenant, only: [:show, :edit, :update, :destroy, :new, :create, :users, :add_user]

  # GET /projects
  # GET /projects.json
  def index
    @all_projects = Project.by_user_plan_and_tenant(params[:tenant_id], current_user)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    comments = @project.comments.where.not(id: nil).where(task_id: nil)
    @client_comm = comments.where(client_comm: true).order(id: :desc)
    @project_comm = comments.where(client_comm: false).order(id: :desc)
    @artifacts = @project.artifacts.where(task_id: nil)
  end

  # GET /projects/new
  def new
    authorize Project, :can_create_projects?
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    authorize @project, :can_manage_projects?
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.users << current_user
    if @project.save
      redirect_to root_url, notice: 'Project was successfully created.' 
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to root_url, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize @project, :can_manage_projects?
    @project.destroy
    redirect_to root_url, notice: 'Project was successfully destroyed.'
  end

  def  users
    authorize @project, :can_manage_projects?
    @project_users = ((@project.users.where.not(role: "admin") + @tenant.users.where(role: "admin")) - [current_user]).sort_by &:email
    @other_users = (@tenant.users - (@project_users + [current_user])).sort_by &:email
  end

  def add_user
    @project_user = UserProject.new(user_id: params[:user_id], project_id: @project.id)

    if @project_user.save
      redirect_to users_tenant_project_url(id: @project.id, tenant_id: @project.tenant_id), notice: "User was succesfullty added to project"
    else
      redirect_to users_tenant_project_url(id: @project.id, tenant_id: @project.tenant_id), error: "User was not added to project"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :details, :expected_start_date, :expected_completion_date, :tenant_id)
    end

    def set_tenant
      @tenant = Tenant.find(params[:tenant_id])
    end

    def verify_tenant
      unless params[:tenant_id] == Tenant.current_tenant_id.to_s
        redirect_to :root, flash: { error: 'You are not authorized to access this page'}
      end
    end

end

app/helpers/project_helper.rb
module ProjectHelper

  def project_status(project)
    if (project.expected_start_date < Date.today) && (project.expected_completion_date > Date.today)
      "In progress"
    elsif project.expected_completion_date < Date.today
      "Completed"
    elsif project.expected_start_date > Date.today
      "In planning"
    end
  end
end

app/views/projects/tabs/_overview.html.haml
.row
  .col-lg-7
    .row
      .col-lg-12
        %p
          %strong Details:
          .well.details-well.well-light
            = @project.details
    .row
      .col-lg-12
        %p
          %strong Clients:
          .well.well-sm.well-light
            - if @project.users.client.empty?
              = '-'
            -else
              - @project.users.client.each.each_with_index do |client, index|
                %span.link>
                  = link_to client.email, user_path(id: client.id), class: 'link-red'
                  - unless index == @project.users.client.size - 1
                    |
    .row
      .col-lg-12
        %p
          %strong Account managers:
          .well.well-sm.well-light
            - if @project.users.account_manager.empty?
              = '-'
            -else
              - @project.users.account_manager.each_with_index do |account_manager, index|
                %span.link>
                  = link_to account_manager.email, user_path(id: account_manager.id), class: 'link-red'
                  - unless index == @project.users.account_manager.size - 1
                    |
    .row
      .col-lg-12
        %p
          %strong Graphic designers:
          .well.well-sm.well-light
            - if @project.users.graphic_designer.empty?
              = '-'
            -else
              - @project.users.graphic_designer.each_with_index do |graphic_designer, index|
                %span.link>
                  = link_to graphic_designer.email, user_path(id: graphic_designer.id), class: 'link-red'
                  - unless index == @project.users.graphic_designer.size - 1
                    |
    .row
      .col-lg-12
        %p
          %strong Copywriters:
          .well.well-sm.well-light
            - if @project.users.copywriter.empty?
              = '-'
            -else
              - @project.users.copywriter.each_with_index  do |copywriter, index|
                %span.link>
                  = link_to copywriter.email, user_path(id: copywriter.id), class: 'link-red'
                  - unless index == @project.users.copywriter.size - 1
                    |
  .col-lg-5
    .row
      .col-lg-4
        %p
          %strong Start date:
          .well.well-sm.well-light
            = @project.expected_start_date
      .col-lg-4
        %p
          %strong Completion date:
          .well.well-sm.well-light
            = @project.expected_completion_date
      .col-lg-4
        %p
          %strong Status:
          .well.well-sm.well-light
            = project_status(@project)
    .row
      .col-lg-4
        %p
          %strong Tasks:
          .well.well-sm.well-light
            = @project.tasks.count
      .col-lg-4
        %p
          %strong Completed tasks:
          .well.well-sm.well-light
            = @project.tasks.published.count
      .col-lg-4
        %p
          %strong Progress:
          .progress.project-progress
            .progress-bar.progress-bar-danger.progress-bar-striped.project-progress-bar.active{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{completed_tasks_percentage(@project)}", :role => "progressbar", :style => "width:#{completed_tasks_percentage(@project)}%"}
              = completed_tasks_percentage(@project) + '%'
    - if policy(@project).can_manage_projects?
      .row
        .col-lg-12
          %strong Actions:
      .row.mt-10
        .col-lg-4
          = link_to 'Edit Project Users', users_tenant_project_path(tenant_id: @project.tenant_id, id: @project.id), :class => 'btn btn-default btn-project-overview'
        .col-lg-4
          = link_to 'Edit Project', edit_tenant_project_path(@project, tenant_id: @tenant.id), :class => 'btn btn-default btn-project-overview'
        .col-lg-4
          = link_to 'Delete Project', tenant_project_path(@project, tenant_id: @tenant.id), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-project-overview'

app/views/projects/tabs/_tasks.html.haml
- if tasks.empty?
  %p.text-center.mb-50 There are no tasks yet.
- else
  .row
    .col-lg-12.pl-30.pr-30.mb-50
      %table.table.table-striped.mt-30
        %thead.row
          %tr
            %th.col-lg-3  Name
            %th.col-lg-4  Description
            %th.col-lg-1  Start date
            %th.col-lg-1  End date
            %th.col-lg-1  Status
            %th.col-lg-1  Priority
            %th.col-lg-1
        %tbody
          - tasks.each do |task|
            %tr.task
              %td= link_to task.name, tenant_project_task_path(task, project_id: @project.id, tenant_id: @tenant.id), class: 'link-red'
              %td= task.description
              %td= task.start_date
              %td= task.end_date
              %td= task.status.humanize
              %td
                - if task.priority == 'low'
                  %span.label.label-success Low
                - if task.priority == 'medium'
                  %span.label.label-warning Medium
                - if task.priority == 'high'
                  %span.label.label-danger High
              %td.float-right
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_tenant_project_task_path(task, project_id: @project.id, tenant_id: @tenant.id), :class => 'btn btn-default btn-xs'
                = link_to t('.destroy', :default => t("helpers.links.destroy")), tenant_project_tasks_destroy_from_list_path(id: task, project_id: @project.id, tenant_id: @tenant.id), :method => :delete, :remote => true, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
.text-center
  = link_to 'Add task', new_tenant_project_task_path(tenant_id: @tenant.id, project_id: @project.id), :class => 'btn btn-danger'