config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
      resources :comments, :only => [:create, :destroy]
      resources :tasks, :except => [:destroy] do
        resources :subtasks, :only => [:create, :destroy, :update]
      end
      delete 'tasks/destroy_from_list', :to => 'tasks#destroy_from_list'
      delete 'tasks/destroy_from_show', :to => 'tasks#destroy_from_show'
    end
  end
  
  resources :members
  get 'home/index'

  get 'user', to: 'users#show'



  root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

end

app/views/shared/_navbar.html.haml
.container.over-nav
.navbar.navbar-inverse
  .row
    .navbar-header
      .navbar-brand
        = link_to('Coord', root_path, title: 'Coord', class: 'root-link')
    .nav.navbar-nav
      .navbar-organization
        = organization_name current_user
    .nav.navbar-nav
      .navbar-name
        = link_to user_path(id: current_user.id), class: 'edit-user-navbar-link' do
          %i.glyphicon.glyphicon-user.mr-10
          = member_name current_user
    .navbar-right
      %ul.nav.navbar-nav         
        %li.dropdown
          %a.menu-dropdown.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %span.glyphicon.glyphicon-align-justify
          %ul.dropdown-menu.nav-dropdown-menu
            - if policy(Member).new?
              %li= link_to('ADD MEMBERS', new_member_path, title: 'ADD MEMBERS')
            - if policy(Tenant).edit?
              %li= link_to('CHANGE PLAN', edit_plan_path, title: 'CHNAGE PLAN')
            %li= link_to('SETTINGS', edit_user_registration_path, title: 'EDIT PROFILE')
            %li.divider
            %li= link_to('LOGOUT <i class="glyphicon glyphicon-log-out"></i>'.html_safe, destroy_user_session_path, title: 'LOGOUT', :method => :delete) 