config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
      resources :comments, :only => [:create, :destroy]
      resources :tasks, :except => [:destroy] do
        resources :subtasks, :only => [:create, :destroy, :update]
      end
      delete 'tasks/destroy_from_list', :to => 'tasks#destroy_from_list'
      delete 'tasks/destroy_from_show', :to => 'tasks#destroy_from_show'
    end
  end
  
  resources :members
  get 'home/index'

  get 'user', to: 'users#show'



  root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

end

app/models/project.rb
class Project < ApplicationRecord

  acts_as_tenant
  belongs_to :tenant
  validates_uniqueness_of :title
  has_many :comments, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :artifacts, dependent: :destroy
  has_many :subtasks, dependent: :destroy
  has_many :user_projects, :dependent => :destroy
  has_many :users, through: :user_projects

  validate :free_plan_can_only_have_one_project

  def free_plan_can_only_have_one_project
    if self.new_record? && (tenant.projects.count > 0) && (tenant.plan == 'free')
      errors.add(:base, "Free plan account can only have one project")
    end
  end

  def self.by_user_plan_and_tenant(tenant_id, user)
    tenant = Tenant.find(tenant_id)
    if tenant.plan == 'premium'
      if user.is_admin? || user.is_account_manager?
        tenant.projects
      else
        user.projects.where(tenant_id: tenant.id)
      end
    else
      if user.is_admin? || user.is_account_manager?
        tenant.projects.order(:id).limit(1)
      else
        user.projects.where(tenant_id: tenant.id).order(:id).limit(1)
      end
    end
  end

  def self.current_projects(tenant_id, user)
    tenant = Tenant.find(tenant_id)
    if tenant.plan == 'premium'
      if user.is_admin? || user.is_account_manager?
        tenant.projects.where("expected_start_date < ? AND expected_completion_date > ?", Date.today, Date.today)
      else
        user.projects.where("tenant_id = ? AND expected_start_date < ? AND expected_completion_date > ?", tenant.id, Date.today, Date.today)
      end
    else
      if user.is_admin? || user.is_account_manager?
        tenant.projects.where("expected_start_date < ? AND expected_completion_date > ?", Date.today, Date.today).order(:id).limit(1)
      else
        user.projects.where("tenant_id = ? AND expected_start_date < ? AND expected_completion_date > ?", tenant.id, Date.today, Date.today).order(:id).limit(1)
      end
    end
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :verify_tenant
  before_action :set_project, only: [:show, :edit, :update, :destroy, :users, :add_user]
  before_action :set_tenant, only: [:show, :edit, :update, :destroy, :new, :create, :users, :add_user]

  # GET /projects
  # GET /projects.json
  def index
    @all_projects = Project.by_user_plan_and_tenant(params[:tenant_id], current_user)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    comments = @project.comments.where.not(id: nil).where(task_id: nil)
    @client_comm = comments.where(client_comm: true).order(id: :desc)
    @project_comm = comments.where(client_comm: false).order(id: :desc)
    @artifacts = @project.artifacts.where(task_id: nil)
  end

  # GET /projects/new
  def new
    authorize Project, :can_create_projects?
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    authorize @project, :can_manage_projects?
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.users << current_user
    if @project.save
      redirect_to root_url, notice: 'Project was successfully created.' 
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to root_url, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize @project, :can_manage_projects?
    @project.destroy
    redirect_to root_url, notice: 'Project was successfully destroyed.'
  end

  def  users
    authorize @project, :can_manage_projects?
    @project_users = ((@project.users.where.not(role: "admin") + @tenant.users.where(role: "admin")) - [current_user]).sort_by &:email
    @other_users = (@tenant.users - (@project_users + [current_user])).sort_by &:email
  end

  def add_user
    @project_user = UserProject.new(user_id: params[:user_id], project_id: @project.id)

    if @project_user.save
      redirect_to users_tenant_project_url(id: @project.id, tenant_id: @project.tenant_id), notice: "User was succesfullty added to project"
    else
      redirect_to users_tenant_project_url(id: @project.id, tenant_id: @project.tenant_id), error: "User was not added to project"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :details, :expected_start_date, :expected_completion_date, :tenant_id)
    end

    def set_tenant
      @tenant = Tenant.find(params[:tenant_id])
    end

    def verify_tenant
      unless params[:tenant_id] == Tenant.current_tenant_id.to_s
        redirect_to :root, flash: { error: 'You are not authorized to access this page'}
      end
    end

end

app/helpers/project_helper.rb
module ProjectHelper

  def project_status(project)
    if (project.expected_start_date < Date.today) && (project.expected_completion_date > Date.today)
      "In progress"
    elsif project.expected_completion_date < Date.today
      "Completed"
    elsif project.expected_start_date > Date.today
      "In planning"
    end
  end
end

app/views/projects/_all.html.haml
.panel.panel-default.signed-in-panel-default
  .panel-heading.default-panel-heading
    %h2 
      PROJECTS
  .panel-body.pt-30
    - if @all_projects.empty?
      %p.text-center You have no projects.
    - else
      %ul.nav.nav-tabs.projects-menu-nav-tabs
        %li.active
          %a{"data-toggle" => "tab", :href => "#all_projects", class: 'red-link'} All projects
        %li
          %a{"data-toggle" => "tab", :href => "#current_projects"} Current projects
        %li
          %a{"data-toggle" => "tab", :href => "#future_projects"} Future projects
        %li
          %a{"data-toggle" => "tab", :href => "#past_projects"} Past projects
      .tab-content.mt-50
        #all_projects.tab-pane.fade.in.active
          = render 'projects/list', projects: @all_projects
        #current_projects.tab-pane.fade
          = render 'projects/list', projects: @current_projects
        #future_projects.tab-pane.fade
          = render 'projects/list', projects: @future_projects
        #past_projects.tab-pane.fade
          = render 'projects/list', projects: @past_projects
    - if @tenant.can_create_projects? && current_user.can_create_projects?
      .text-center.mt-50
        = link_to 'New Project', new_tenant_project_path(tenant_id: @tenant.id), :class => 'btn btn-danger'

app/views/projects/_list.html.haml
- if @all_projects.empty?
  %p.text-center There are no projects fulfilling this criteria.
- else
  = search_form_for @q, url: root_path do |f|
    .form-group.mb-50
      .row
        .col-lg-2
        .col-lg-3
          = f.label :title_cont, 'Title contains:'
        .col-lg-4
          = f.label :details_cont, 'Details contain:'
        .col-lg-3
      .row
        .col-lg-2
        .col-lg-3
          = f.search_field :title_cont, class: 'form-control'
        .col-lg-4
          = f.search_field :details_cont, class: 'form-control'
        .col-lg-1
          = f.submit 'Search', class: 'btn btn-danger button-39 full-width'
        .col-lg-2

  %table.table.table-striped
    %thead
      %th.col-lg-3= sort_link @q, :title, default_order: :asc
      %th.col-lg-4 Details
      %th.col-lg-1= sort_link @q, :expected_start_date, 'Start date'
      %th.col-lg-1= sort_link @q, :expected_completion_date, 'Completion date'
      %th.col-lg-2
    %tbody
      - projects.each do |project|
        %tr
          %td= link_to project.title, tenant_project_path(project, tenant_id: @tenant.id), class: 'link-red'
          %td= project.details
          %td= project.expected_start_date
          %td= project.expected_completion_date
          %td.float-right
            - if policy(project).can_manage_projects?
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_tenant_project_path(project, tenant_id: @tenant.id), :class => 'btn btn-default btn-xs'
              = link_to 'Edit Users', users_tenant_project_path(project, tenant_id: @tenant.id), :class => 'btn btn-default btn-xs'
              = link_to t('.destroy', :default => t("helpers.links.destroy")), tenant_project_path(project, tenant_id: @tenant.id), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/projects/edit.html.haml
- unless flash[:error].nil?
  .alert.fade.in.alert-danger
    %button.close{"data-dismiss" => "alert", :type => "button"} ×
    = flash[:error]
.panel.panel-default.signed-in-panel-default
  .panel-heading.default-panel-heading
    %h2   
      %strong Update
      = @project.title
  .panel-body.pt-30   
    = form_for [@tenant, @project] do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', required: true
      .form-group
        = f.label :details
        = f.text_area :details, class: 'form-control', required: true
      .form-group
        = f.label :expected_start_date
        = f.text_field :expected_start_date, class: 'form-control datepicker', required: true
      .form-group
        = f.label :expected_completion_date
        = f.text_field :expected_completion_date, class: 'form-control datepicker', required: true
      = f.hidden_field :tenant_id, value: params[:tenant_id], class: 'form-control'
      .text-center
        = f.submit 'Update project',class: 'btn btn-danger mt-30'
.text-center.mt-30                       
  = link_to 'Back', tenant_project_path(id: @project.id, tenant_id: @project.tenant_id), :class => 'link-red'

app/views/projects/new.html.haml
- unless flash[:error].nil?
  .alert.fade.in.alert-danger
    %button.close{"data-dismiss" => "alert", :type => "button"} ×
    = flash[:error]
.panel.panel-default.signed-in-panel-default
  .panel-heading.default-panel-heading
    %h2   
      %strong CREATE PROJECT
  .panel-body.pt-30   
    = form_for [@tenant, @project] do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', required: true
      .form-group
        = f.label :details
        = f.text_area :details, class: 'form-control', required: true
      .form-group
        = f.label :expected_start_date
        = f.text_field :expected_start_date, class: 'form-control datepicker', required: true
      .form-group
        = f.label :expected_completion_date
        = f.text_field :expected_completion_date, class: 'form-control datepicker', required: true
      = f.hidden_field :tenant_id, value: params[:tenant_id], class: 'form-control'
      .text-center
        = f.submit 'Create project',class: 'btn btn-danger mt-30'
.text-center.mt-30                       
  = link_to 'Back', root_path, :class => 'link-red'

app/views/projects/show.html.haml
.panel.panel-default.signed-in-panel-default
  .panel-heading.default-panel-heading
    %h2 
      %strong PROJECT: 
      = @project.title
  .panel-body.pt-30
    %ul.nav.nav-tabs.projects-menu-nav-tabs
      %li.active
        %a{"data-toggle" => "tab", :href => "#overview", class: 'red-link'} Overview
      %li
        %a{"data-toggle" => "tab", :href => "#client_communication"} 
          Client communication
          %span.badge#client-comm-count
            = @client_comm.count
      - unless current_user.is_client?
        %li
          %a{"data-toggle" => "tab", :href => "#comments"} 
            Comments
            %span.badge#project-comm-count
              = @project_comm.count
      %li
        %a{"data-toggle" => "tab", :href => "#tasks"} 
          Tasks
          %span.badge#tasks-count
            = @project.tasks.count
      %li
        %a{"data-toggle" => "tab", :href => "#attachments"} 
          Attachments
          %span.badge#artifacts-count
            = @artifacts.count
    .tab-content.mt-50
      #overview.tab-pane.fade.in.active
        = render 'projects/tabs/overview'
      #client_communication.tab-pane.fade
        = render 'projects/tabs/comments', comments: @client_comm, is_client_com: true
      #comments.tab-pane.fade
        = render 'projects/tabs/comments', comments: @project_comm, is_client_com: false
      #tasks.tab-pane.fade
        = render 'projects/tabs/tasks', tasks: @project.tasks
      #attachments.tab-pane.fade
        = render 'artifacts/list', artifacts: @artifacts, task_id: ""
.text-center.mt-30                       
  = link_to 'Back', root_path, :class => 'link-red'

app/views/projects/users.html.haml
.panel.panel-default.signed-in-panel-default
  .panel-heading.default-panel-heading
    %h2 
      Users for project 
      %strong #{@project.title}
    %p (Other than yourself)
  .panel-body.pt-30
    - if @project_users.empty?
      %p.text-center There are no users added to this project.
    - else
      %table.table.table-striped.table-users
        %thead.row
          %tr
            %th.col-lg-5 Email
            %th.col-lg-5 Role
            %th.col-lg-2
        %tbody
          - @project_users.each do |project_user|
            %tr
              %td= link_to project_user.email, user_path(id: project_user.id), class: 'link-red'
              %td= project_user.role.humanize
              %td
                - if !project_user.is_admin?
                  = link_to 'Remove', user_project_path(project_user.user_projects.find_by(project_id: @project.id), tenant_id: @project.tenant_id), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger btn-add-remove'
.panel.panel-default.signed-in-panel-default
  .panel-heading.default-panel-heading
    %h2 
      Users to add to project 
      %strong #{@project.title}
    %p (Admins don't need to be added)
  .panel-body.pt-30
    - if @other_users.empty?
      %p.text-center There are no users available.
    - else
      %table.table.table-striped.table-users
        %thead.row
          %tr
            %th.col-lg-5 Email
            %th.col-lg-5 Role
            %th.col-lg-2
        %tbody
          - @other_users.each do |other_user|
            %tr
              %td= link_to other_user.email, user_path(id: other_user.id), class: 'link-red'
              %td= other_user.role.humanize
              %td
                = link_to 'Add',                                                                                        
                  add_user_tenant_project_path(id: @project.id, tenant_id: @project.tenant_id, user_id: other_user.id), :method => :put, :class => 'btn btn-xs btn-success btn-add-remove'                                           
.text-center.mt-30                       
  = link_to 'Back', tenant_project_path(id: @project.id, tenant_id: @project.tenant_id), :class => 'link-red'