config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
      resources :comments, :only => [:create, :destroy]
      resources :tasks, :except => [:destroy] do
        resources :subtasks, :only => [:create, :destroy, :update]
      end
      delete 'tasks/destroy_from_list', :to => 'tasks#destroy_from_list'
      delete 'tasks/destroy_from_show', :to => 'tasks#destroy_from_show'
    end
  end
  
  resources :members
  get 'home/index'

  get 'user', to: 'users#show'



  root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan

end

app/models/task.rb
class Task < ApplicationRecord
  acts_as_tenant
  belongs_to :tenant
  belongs_to :project
  validates_presence_of :name
  validates_presence_of :status
  has_many :comments, dependent: :destroy
  has_many :artifacts, dependent: :destroy
  has_many :subtasks, dependent: :destroy

  enum status: {defined: 0, in_progress: 1, completed: 2, account_acceptance: 3, client_acceptance: 4, published: 5}
  enum priority: {low: 0, medium: 1, high: 2}
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy_from_list, :destroy_from_show]
  before_action :set_project, only: [:show, :edit, :update, :destroy_from_list, :destroy_from_show, :new, :create]
  before_action :set_tenant, only: [:show, :edit, :update, :destroy_from_list, :destroy_from_show, :new, :create]

  def new
    authorize Task, :can_create_tasks?
    @task = Task.new
  end

  def create
    authorize Task, :can_create_tasks?
    @task = Task.new(task_params)
    if @task.save
      redirect_to tenant_project_path(id: @project.id, tenant_id: @tenant.id), notice: 'Task was successfully created.' 
    else
      render :new
    end
  end

  def destroy_from_list
    if @task.destroy
      render :json => @task, :status => :ok 
    else
      render :js => "alert('error deleting task');" 
    end
  end

  def destroy_from_show
    if @task.destroy
      redirect_to tenant_project_path(id: @project.id, tenant_id: @tenant.id), notice: 'Task was successfully deleted.'
    else
      redirect_to tenant_project_path(id: @project.id, tenant_id: @tenant.id), error: 'Task could not be deleted.'
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tenant_project_task_path(id: @task.id, project_id: @project.id, tenant_id: @tenant.id), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def show
    comments = @task.comments.where.not(id: nil)
    @client_comm = comments.where(client_comm: true).order(id: :desc)
    @project_comm = comments.where(client_comm: false).order(id: :desc)
    @subtasks = @task.subtasks.where.not(id: nil).order(id: :desc)
  end

  private

    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :start_date, :end_date, :status, :priority, :tenant_id, :project_id)
    end

    def set_tenant
      @tenant = Tenant.find(params[:tenant_id])
    end

end

app/views/tasks/tabs/_comments.html.haml
.row
  .col-lg-12.pl-30.pr-30
    = render "comments/form", is_client_com: is_client_com
    - unless comments.empty?
      .comments
        = render :partial => 'comments/comment', :collection => comments

app/views/tasks/tabs/_overview.html.haml
.row
  .col-lg-7
    .row
      .col-lg-12
        %p
          %strong Details:
          .well.details-well.well-light
            = @task.description
  .col-lg-5
    .row
      .col-lg-4
        %p
          %strong Start date:
          .well.well-sm.well-light
            = @task.start_date
      .col-lg-4
        %p
          %strong Completion date:
          .well.well-sm.well-light
            = @task.end_date
      .col-lg-4
        %p
          %strong Priority:
          .well.well-sm.well-light
            = @task.priority.humanize
    .row
      .col-lg-4
        %p
          %strong Status:
          .well.well-sm.well-light
            = @task.status.humanize
      .col-lg-8
        %p
          %strong Progress:
          .progress.project-progress
            .progress-bar.progress-bar-danger.progress-bar-striped.project-progress-bar.active{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{task_progress_percentage(@task)}", :role => "progressbar", :style => "width:#{task_progress_percentage(@task)}%"}
              = task_progress_percentage(@task) + '%'
    - if policy(@project).can_manage_projects?
      .row
        .col-lg-12
          %strong Actions:
      .row.mt-10
        .col-lg-6
          = link_to 'Edit Task', edit_tenant_project_task_path(@task, project_id: @project.id, tenant_id: @tenant.id), :class => 'btn btn-default btn-project-overview'
        .col-lg-6
          = link_to 'Delete Task', tenant_project_tasks_destroy_from_show_path(id: @task, project_id: @project.id, tenant_id: @tenant.id), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-project-overview'
.row.mt-50
  %h3.text-center
    %strong
      = 'SUBTASKS' 
      #subtask-count
        = @subtasks.count
  .col-lg-12.pl-30.pr-30
    = render "subtasks/form"
    - unless @subtasks.empty?
      .subtasks
        = render :partial => 'subtasks/subtask', :collection => @subtasks